version: '2'
services:
    smarttrackingbeacons-app:
        image: smarttrackingbeacons
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://smarttrackingbeacons-mssql:1433;database=SmartTrackingBeacons
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smarttrackingbeacons-mssql:
        extends:
            file: mssql.yml
            service: smarttrackingbeacons-mssql
